method: campari
data:
  ds_path: data/chairs1/*/image/
  dataset: chairs1
training:
  batch_size_pg: [64, 20, 15]
  pg_n_loop_final: 3
  n_workers: [12, 5, 0]
  pg_milestones: [20000, 70000]
model:
  out_folder: out/chairs1
  generator_kwargs:
    #test_fit_gaussian: True
    init_pose_iter: 1000
    camera_param: full
    gt_stats_file: data/stats_files/chairs1.npz
    raw_noise_std: 2.
    n_samples_ps: [32, 42, 52]
    white_background: True
    fov_range: [49.1, 0.]
  latent_cameras: embed_full4
  decoder_bg: null
test:
  n_test_samples_train: 64
  n_test_samples_test: 64

